[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0F766E"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#E7F0F2"
textColor = "#1F2937"
font = "sans serif"
